# -*- coding: utf-8 -*-
"""Part 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OhejPgYpSm4Zb0dCFBUzcdKxpH2AVDNC
"""

import statistics

data = [68,34,47,67,12,76,28,5,74,1,2,96,64,91,17,38,83,29,41,100,73,16,41,7,24,89,4,92,88,52,9,10,72,19,96,34,88,19,7,17,79,91,85,11,22,9,77,58,45,24,92,33,47,54,5,97,27,11,79,77,70,11,96,61,50,76,19,99,54,87,2,13,43,12,13,39,91,76,97,60,86,61,42,52,35,18,75,46,33,38,88,72,31,8,86,13,96,36,52,59]

x = statistics.mean(data)
y = statistics.median(data)
z = statistics.mode(data)

print('mean:',x)
print('median:',y)
print('mode:',z)